language: r
r:
  - 3.5.2

dist: xenial

cache:
  packages: true
  directories:
    - _bookdown_files
    - $HOME/.npm
    
latex: false
branches:
  only:
    - master
    - release
    - stable

pandoc_version: 2.7.2

env:
  global:
    - TZ="Asia/Shanghai"
    - MAKEFLAGS="-j 4"
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

git:
  depth: 10
  submodules: false
  
repos:
  CRAN: https://cloud.r-project.org

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ghostscript
      - optipng
      - g++-8
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

before_install:
  - mkdir -p ~/.R/
  - echo "CXXFLAGS += -Wno-ignored-attributes" >> ~/.R/Makevars
  - echo "CXX14 = g++-8 -fPIC -flto=2" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars
  - npm install netlify-cli -g

before_script:
  - Rscript -e 'update.packages(lib.loc = .libPaths()[1], ask = FALSE)'

script:
  - Rscript -e 'bookdown::render_book("index.Rmd")'

deploy:
  - provider: script
    script: netlify deploy --prod --dir _book
    skip_cleanup: true
    on:
      branch: master
