language: r
dist: xenial
services:
  - docker
cache:
  packages: true
  directories:
    - _bookdown_files
    - $HOME/.npm
    
latex: false
pandoc: false

before_install:
  # install stable node
  - nvm install stable  
  - npm install netlify-cli -g
  # deploy with messages 
  - export COMMIT_MSG=$(git log -1 --format='%h %<(50,trunc)%s')
  - echo $COMMIT_MSG
  - export DEPLOY_MSG=${COMMIT_MSG//[\'\"\`]/}
  - echo $DEPLOY_MSG
  - docker pull ${DOCKER_REPO_FEDORA30}
  - chmod +x ./_build.sh

script:
  - docker run --rm ${DOCKER_REPO_FEDORA30} Rscript -e "sessionInfo(.packages(T))"
  - docker run --rm ${DOCKER_REPO_FEDORA30} Rscript -e "parallel::detectCores()"
  - docker run --rm --name "book" -u root -v "/${PWD}://home/docker/workspace" ${DOCKER_REPO_FEDORA30} sh ./_build.sh

deploy:
  provider: script
  script: netlify deploy --prod --dir _book --message "$DEPLOY_MSG"
  skip_cleanup: true
  on:
    branch: master
